---
title: "Untitled"
author: "kevin"
date: "December 29, 2020"
output: html_document
---
```{r}
data<- read.csv("activity.csv")
summary(data)
```

## What is mean total number of steps taken per day?
```{r}
library(ggplot2)
steps_day<- with(data,tapply(steps,date,sum,na.rm=TRUE))
qplot(steps_day, xlab="total number of steps taken each day")
```
#mean steps taken per day
```{r}
mean(steps_day)
```
#median steps taken per day
```{r}
median(steps_day)
```
##What is the average daily activity pattern?
```{r warning=TRUE}
library(dplyr)
averages <- aggregate(x=list(steps=data$steps), by=list(interval=data$interval),
                      FUN=mean, na.rm=TRUE)
ggplot(data=averages, aes(x=interval, y=steps)) +
    geom_line() +
    xlab("5-minute interval") +
    ylab("average number of steps taken")
```
#Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
```{r}
averages[which.max(averages$steps),]
```
## missing values
```{r}
sum(is.na(data$steps))
```
##  impute missing values
```{r}
install.packages("class")
library(class)
knnImputation(data$steps, k = 10, scale = T, meth = "median",
              distData = data$interval)
```